package com.cestasdamel.erp;
import com.cestasdamel.erp.dto.Requests.*; import com.cestasdamel.erp.dto.Responses.*; import com.cestasdamel.erp.exception.BusinessException; import com.cestasdamel.erp.model.Enums.*; import com.cestasdamel.erp.repository.*; import com.cestasdamel.erp.service.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.test.context.ActiveProfiles; import java.math.BigDecimal; import java.util.List; import static org.assertj.core.api.Assertions.*;
@SpringBootTest @ActiveProfiles("test")
class ErpWorkflowIntegrationTests {
 @Autowired CatalogService catalog; @Autowired InventoryService inventory; @Autowired OperationsService operations; @Autowired FinanceService finance;
 @Autowired ProductRepository products; @Autowired MaterialRepository materials; @Autowired BasketTemplateRepository baskets; @Autowired SaleRepository sales; @Autowired PurchaseRepository purchases; @Autowired ExpenseRepository expenses; @Autowired FinancialTransactionRepository transactions; @Autowired StockMovementRepository stockMovements; @Autowired MaterialMovementRepository materialMovements;
 @BeforeEach void clean(){transactions.deleteAll();stockMovements.deleteAll();materialMovements.deleteAll();sales.deleteAll();purchases.deleteAll();expenses.deleteAll();baskets.deleteAll();products.deleteAll();materials.deleteAll();}
 @Test void completePurchaseAssemblySaleAndCashFlow(){
  ProductView product=catalog.saveProduct(null,new ProductInput("Chocolate",null,UnitOfMeasure.UNIT,new BigDecimal("2"),new BigDecimal("4"),new BigDecimal("8"),true)); MaterialView material=catalog.saveMaterial(null,new MaterialInput("Caixa",null,UnitOfMeasure.UNIT,BigDecimal.ONE,new BigDecimal("3"),true));
  PurchaseView purchase=operations.purchase(new PurchaseInput("Fornecedor",null,null,List.of(new PurchaseLine(ItemType.PRODUCT,product.id(),new BigDecimal("10"),new BigDecimal("4")),new PurchaseLine(ItemType.MATERIAL,material.id(),new BigDecimal("5"),new BigDecimal("3"))))); assertThat(purchase.total()).isEqualByComparingTo("55.00");
  BasketView basket=catalog.saveBasket(null,new BasketInput("Cesta",null,new BigDecimal("25"),true,List.of(new CompositionItem(product.id(),new BigDecimal("2"))),List.of(new CompositionItem(material.id(),BigDecimal.ONE)))); assertThat(operations.assemble(basket.id(),new Assembly(2,"teste")).assembledQuantity()).isEqualTo(2);
  SaleView sale=operations.sale(new SaleInput(null,PaymentMethod.PIX,null,List.of(new SaleLine(ItemType.BASKET,basket.id(),BigDecimal.ONE,null),new SaleLine(ItemType.PRODUCT,product.id(),BigDecimal.ONE,null)))); assertThat(sale.total()).isEqualByComparingTo("33.00"); assertThat(catalog.products().getFirst().quantity()).isEqualByComparingTo("5.000"); assertThat(catalog.materials().getFirst().quantity()).isEqualByComparingTo("3.000"); assertThat(catalog.basket(basket.id()).assembledQuantity()).isEqualTo(1); assertThat(finance.balance()).isEqualByComparingTo("-22.00"); assertThat(inventory.stockHistory(product.id())).hasSize(3); assertThat(inventory.materialHistory(material.id())).hasSize(2);
 }
 @Test void insufficientStockRollsBackEntireAssembly(){
  ProductView product=catalog.saveProduct(null,new ProductInput("Chocolate",null,UnitOfMeasure.UNIT,BigDecimal.ZERO,BigDecimal.ONE,BigDecimal.TEN,true)); MaterialView material=catalog.saveMaterial(null,new MaterialInput("Caixa",null,UnitOfMeasure.UNIT,BigDecimal.ZERO,BigDecimal.ONE,true)); inventory.adjustProduct(product.id(),new InventoryAdjustment(BigDecimal.ONE,"inicial")); inventory.adjustMaterial(material.id(),new InventoryAdjustment(BigDecimal.ONE,"inicial"));
  BasketView basket=catalog.saveBasket(null,new BasketInput("Cesta",null,BigDecimal.TEN,true,List.of(new CompositionItem(product.id(),BigDecimal.ONE)),List.of(new CompositionItem(material.id(),BigDecimal.ONE)))); assertThatThrownBy(()->operations.assemble(basket.id(),new Assembly(2,"não deve gravar"))).isInstanceOf(BusinessException.class).hasMessageContaining("Estoque insuficiente"); assertThat(catalog.products().getFirst().quantity()).isEqualByComparingTo("1.000"); assertThat(catalog.materials().getFirst().quantity()).isEqualByComparingTo("1.000"); assertThat(catalog.basket(basket.id()).assembledQuantity()).isZero(); assertThat(inventory.stockHistory(product.id())).hasSize(1); assertThat(inventory.materialHistory(material.id())).hasSize(1);
 }
}
