package com.cestasdamel.erp.service;
import com.cestasdamel.erp.dto.Requests.*; import com.cestasdamel.erp.dto.Responses.*; import com.cestasdamel.erp.exception.*; import com.cestasdamel.erp.model.*; import com.cestasdamel.erp.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @RequiredArgsConstructor
public class CatalogService {
 private final ProductRepository products; private final MaterialRepository materials; private final BasketTemplateRepository baskets;
 @Transactional(readOnly=true) public List<ProductView> products(){return products.findAllByOrderByNameAsc().stream().map(ViewMapper::product).toList();}
 @Transactional public ProductView saveProduct(Long id,ProductInput r){Product p=id==null?new Product():products.findById(id).orElseThrow(()->new NotFoundException("Produto",id));p.setName(r.name());p.setDescription(r.description());p.setUnit(r.unit());p.setMinimumStock(r.minimumStock());p.setPurchasePrice(r.purchasePrice());p.setSalePrice(r.salePrice());if(r.active()!=null)p.setActive(r.active());return ViewMapper.product(products.save(p));}
 @Transactional(readOnly=true) public List<MaterialView> materials(){return materials.findAllByOrderByNameAsc().stream().map(ViewMapper::material).toList();}
 @Transactional public MaterialView saveMaterial(Long id,MaterialInput r){Material m=id==null?new Material():materials.findById(id).orElseThrow(()->new NotFoundException("Material",id));m.setName(r.name());m.setDescription(r.description());m.setUnit(r.unit());m.setMinimumStock(r.minimumStock());m.setUnitCost(r.unitCost());if(r.active()!=null)m.setActive(r.active());return ViewMapper.material(materials.save(m));}
 @Transactional(readOnly=true) public List<BasketView> baskets(){return baskets.findAllDetailed().stream().map(ViewMapper::basket).toList();}
 @Transactional(readOnly=true) public BasketView basket(Long id){return ViewMapper.basket(baskets.findDetailed(id).orElseThrow(()->new NotFoundException("Cesta",id)));}
 @Transactional public BasketView saveBasket(Long id,BasketInput r){BasketTemplate b=id==null?new BasketTemplate():baskets.findDetailed(id).orElseThrow(()->new NotFoundException("Cesta",id));b.setName(r.name());b.setDescription(r.description());b.setSalePrice(r.salePrice());if(r.active()!=null)b.setActive(r.active());b.getProducts().clear();Set<Long> seen=new HashSet<>();for(CompositionItem x:r.products()){if(!seen.add(x.id()))throw new BusinessException("Produto repetido na composição: "+x.id());BasketProduct c=new BasketProduct();c.setBasket(b);c.setProduct(products.findById(x.id()).orElseThrow(()->new NotFoundException("Produto",x.id())));c.setQuantity(x.quantity());b.getProducts().add(c);}b.getMaterials().clear();seen.clear();for(CompositionItem x:r.materials()){if(!seen.add(x.id()))throw new BusinessException("Material repetido na composição: "+x.id());BasketMaterial c=new BasketMaterial();c.setBasket(b);c.setMaterial(materials.findById(x.id()).orElseThrow(()->new NotFoundException("Material",x.id())));c.setQuantity(x.quantity());b.getMaterials().add(c);}return ViewMapper.basket(baskets.save(b));}
}
