package com.cestasdamel.erp.service;
import com.cestasdamel.erp.dto.Requests.InventoryAdjustment; import com.cestasdamel.erp.dto.Responses.*; import com.cestasdamel.erp.exception.*; import com.cestasdamel.erp.model.*; import com.cestasdamel.erp.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@Service @RequiredArgsConstructor public class InventoryService {
 private final ProductRepository products; private final MaterialRepository materials; private final BasketTemplateRepository baskets; private final StockMovementRepository stocks; private final MaterialMovementRepository materialMoves; private final BasketMovementRepository basketMoves; private final UnitConversionService units;
 @Transactional public ProductView adjustProduct(Long id,InventoryAdjustment r){Product p=lockProduct(id);BigDecimal q=units.convert(r.quantity(),r.unit(),p.getUnit());BigDecimal next=p.getQuantity().add(q);if(next.signum()<0)throw new BusinessException("Ajuste deixaria o produto com estoque negativo");p.setQuantity(next);stock(p,q.signum()>=0?Enums.MovementType.IN:Enums.MovementType.OUT,Enums.MovementReason.ADJUSTMENT,q.abs(),null,r.notes(),Instant.now());return ViewMapper.product(p);}
 @Transactional public MaterialView adjustMaterial(Long id,InventoryAdjustment r){Material m=lockMaterial(id);BigDecimal q=units.convert(r.quantity(),r.unit(),m.getUnit());BigDecimal next=m.getQuantity().add(q);if(next.signum()<0)throw new BusinessException("Ajuste deixaria o material com estoque negativo");m.setQuantity(next);material(m,q.signum()>=0?Enums.MovementType.IN:Enums.MovementType.OUT,Enums.MovementReason.ADJUSTMENT,q.abs(),null,r.notes(),Instant.now());return ViewMapper.material(m);}
 public void setProductQuantity(Product p,BigDecimal desired,String notes){if(desired.signum()<0)throw new BusinessException("Estoque do produto não pode ser negativo");BigDecimal delta=desired.subtract(p.getQuantity());if(delta.signum()==0)return;p.setQuantity(desired);stock(p,delta.signum()>0?Enums.MovementType.IN:Enums.MovementType.OUT,Enums.MovementReason.ADJUSTMENT,delta.abs(),null,notes,Instant.now());}
 public void setMaterialQuantity(Material m,BigDecimal desired,String notes){if(desired.signum()<0)throw new BusinessException("Estoque do material não pode ser negativo");BigDecimal delta=desired.subtract(m.getQuantity());if(delta.signum()==0)return;m.setQuantity(desired);material(m,delta.signum()>0?Enums.MovementType.IN:Enums.MovementType.OUT,Enums.MovementReason.ADJUSTMENT,delta.abs(),null,notes,Instant.now());}
 public Product lockProduct(Long id){return products.lockById(id).orElseThrow(()->new NotFoundException("Produto",id));} public Material lockMaterial(Long id){return materials.lockById(id).orElseThrow(()->new NotFoundException("Material",id));} public BasketTemplate lockBasket(Long id){return baskets.lockDetailedById(id).orElseThrow(()->new NotFoundException("Cesta",id));}
 public void remove(Product p,BigDecimal q,Enums.MovementReason reason,Long ref,String notes,Instant at){require(p.getName(),p.getQuantity(),q);p.setQuantity(p.getQuantity().subtract(q));stock(p,Enums.MovementType.OUT,reason,q,ref,notes,at);} public void add(Product p,BigDecimal q,Enums.MovementReason reason,Long ref,String notes,Instant at){p.setQuantity(p.getQuantity().add(q));stock(p,Enums.MovementType.IN,reason,q,ref,notes,at);}
 public void remove(Material m,BigDecimal q,Enums.MovementReason reason,Long ref,String notes,Instant at){require(m.getName(),m.getQuantity(),q);m.setQuantity(m.getQuantity().subtract(q));material(m,Enums.MovementType.OUT,reason,q,ref,notes,at);} public void add(Material m,BigDecimal q,Enums.MovementReason reason,Long ref,String notes,Instant at){m.setQuantity(m.getQuantity().add(q));material(m,Enums.MovementType.IN,reason,q,ref,notes,at);}
 public void remove(BasketTemplate b,BigDecimal q,Enums.MovementReason reason,Long ref,String notes,Instant at){require(b.getName(),b.getStockQuantity(),q);b.setStockQuantity(b.getStockQuantity().subtract(q));basket(b,Enums.MovementType.OUT,reason,q,ref,notes,at);} public void add(BasketTemplate b,BigDecimal q,Enums.MovementReason reason,Long ref,String notes,Instant at){b.setStockQuantity(b.getStockQuantity().add(q));basket(b,Enums.MovementType.IN,reason,q,ref,notes,at);}
 private void require(String name,BigDecimal available,BigDecimal needed){if(available.compareTo(needed)<0)throw new BusinessException("Estoque insuficiente de "+name+". Disponível: "+available+", necessário: "+needed);}
 private void stock(Product p,Enums.MovementType t,Enums.MovementReason r,BigDecimal q,Long ref,String n,Instant at){StockMovement x=new StockMovement();x.setProduct(p);x.setType(t);x.setReason(r);x.setQuantity(q);x.setBalanceAfter(p.getQuantity());x.setReferenceId(ref);x.setNotes(n);x.setOccurredAt(at);stocks.save(x);} private void material(Material m,Enums.MovementType t,Enums.MovementReason r,BigDecimal q,Long ref,String n,Instant at){MaterialMovement x=new MaterialMovement();x.setMaterial(m);x.setType(t);x.setReason(r);x.setQuantity(q);x.setBalanceAfter(m.getQuantity());x.setReferenceId(ref);x.setNotes(n);x.setOccurredAt(at);materialMoves.save(x);} private void basket(BasketTemplate b,Enums.MovementType t,Enums.MovementReason r,BigDecimal q,Long ref,String n,Instant at){BasketMovement x=new BasketMovement();x.setBasket(b);x.setType(t);x.setReason(r);x.setQuantity(q);x.setBalanceAfter(b.getStockQuantity());x.setReferenceId(ref);x.setNotes(n);x.setOccurredAt(at);basketMoves.save(x);}
 @Transactional(readOnly=true) public List<MovementView> stockHistory(Long id){List<StockMovement> xs=id==null?stocks.findAllByOrderByOccurredAtDesc():stocks.findByProductIdOrderByOccurredAtDesc(id);return xs.stream().map(x->new MovementView(x.getId(),x.getProduct().getId(),x.getProduct().getName(),x.getProduct().getUnit(),x.getType(),x.getReason(),signed(x.getType(),x.getQuantity()),x.getBalanceAfter(),x.getReferenceId(),x.getNotes(),x.getOccurredAt())).toList();}
 @Transactional(readOnly=true) public List<MovementView> materialHistory(Long id){List<MaterialMovement> xs=id==null?materialMoves.findAllByOrderByOccurredAtDesc():materialMoves.findByMaterialIdOrderByOccurredAtDesc(id);return xs.stream().map(x->new MovementView(x.getId(),x.getMaterial().getId(),x.getMaterial().getName(),x.getMaterial().getUnit(),x.getType(),x.getReason(),signed(x.getType(),x.getQuantity()),x.getBalanceAfter(),x.getReferenceId(),x.getNotes(),x.getOccurredAt())).toList();}
 @Transactional(readOnly=true) public List<MovementView> basketHistory(Long id){List<BasketMovement> xs=id==null?basketMoves.findAllByOrderByOccurredAtDesc():basketMoves.findByBasketIdOrderByOccurredAtDesc(id);return xs.stream().map(x->new MovementView(x.getId(),x.getBasket().getId(),x.getBasket().getName(),Enums.UnitOfMeasure.UNIT,x.getType(),x.getReason(),signed(x.getType(),x.getQuantity()),x.getBalanceAfter(),x.getReferenceId(),x.getNotes(),x.getOccurredAt())).toList();}
 private BigDecimal signed(Enums.MovementType type,BigDecimal quantity){return type==Enums.MovementType.OUT?quantity.negate():quantity;}
}
