package com.cestasdamel.erp.service;
import com.cestasdamel.erp.dto.Requests.InventoryAdjustment; import com.cestasdamel.erp.dto.Responses.*; import com.cestasdamel.erp.exception.*; import com.cestasdamel.erp.model.*; import com.cestasdamel.erp.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@Service @RequiredArgsConstructor
public class InventoryService {
 private final ProductRepository products; private final MaterialRepository materials; private final StockMovementRepository stocks; private final MaterialMovementRepository materialMoves;
 @Transactional public ProductView adjustProduct(Long id,InventoryAdjustment r){Product p=lockProduct(id);BigDecimal next=p.getQuantity().add(r.quantity());if(next.signum()<0)throw new BusinessException("Ajuste deixaria o produto com estoque negativo");p.setQuantity(next);stock(p,r.quantity().signum()>=0?Enums.MovementType.IN:Enums.MovementType.OUT,Enums.MovementReason.ADJUSTMENT,r.quantity().abs(),null,r.notes(),Instant.now());return ViewMapper.product(p);}
 @Transactional public MaterialView adjustMaterial(Long id,InventoryAdjustment r){Material m=lockMaterial(id);BigDecimal next=m.getQuantity().add(r.quantity());if(next.signum()<0)throw new BusinessException("Ajuste deixaria o material com estoque negativo");m.setQuantity(next);material(m,r.quantity().signum()>=0?Enums.MovementType.IN:Enums.MovementType.OUT,Enums.MovementReason.ADJUSTMENT,r.quantity().abs(),null,r.notes(),Instant.now());return ViewMapper.material(m);}
 public Product lockProduct(Long id){return products.lockById(id).orElseThrow(()->new NotFoundException("Produto",id));} public Material lockMaterial(Long id){return materials.lockById(id).orElseThrow(()->new NotFoundException("Material",id));}
 public void remove(Product p,BigDecimal q,Enums.MovementReason reason,Long ref,String notes,Instant at){if(p.getQuantity().compareTo(q)<0)throw new BusinessException("Estoque insuficiente de "+p.getName()+". Disponível: "+p.getQuantity()+", necessário: "+q);p.setQuantity(p.getQuantity().subtract(q));stock(p,Enums.MovementType.OUT,reason,q,ref,notes,at);}
 public void add(Product p,BigDecimal q,Enums.MovementReason reason,Long ref,String notes,Instant at){p.setQuantity(p.getQuantity().add(q));stock(p,Enums.MovementType.IN,reason,q,ref,notes,at);}
 public void remove(Material m,BigDecimal q,Enums.MovementReason reason,Long ref,String notes,Instant at){if(m.getQuantity().compareTo(q)<0)throw new BusinessException("Estoque insuficiente de "+m.getName()+". Disponível: "+m.getQuantity()+", necessário: "+q);m.setQuantity(m.getQuantity().subtract(q));material(m,Enums.MovementType.OUT,reason,q,ref,notes,at);}
 public void add(Material m,BigDecimal q,Enums.MovementReason reason,Long ref,String notes,Instant at){m.setQuantity(m.getQuantity().add(q));material(m,Enums.MovementType.IN,reason,q,ref,notes,at);}
 private void stock(Product p,Enums.MovementType t,Enums.MovementReason r,BigDecimal q,Long ref,String n,Instant at){StockMovement x=new StockMovement();x.setProduct(p);x.setType(t);x.setReason(r);x.setQuantity(q);x.setBalanceAfter(p.getQuantity());x.setReferenceId(ref);x.setNotes(n);x.setOccurredAt(at);stocks.save(x);}
 private void material(Material m,Enums.MovementType t,Enums.MovementReason r,BigDecimal q,Long ref,String n,Instant at){MaterialMovement x=new MaterialMovement();x.setMaterial(m);x.setType(t);x.setReason(r);x.setQuantity(q);x.setBalanceAfter(m.getQuantity());x.setReferenceId(ref);x.setNotes(n);x.setOccurredAt(at);materialMoves.save(x);}
 @Transactional(readOnly=true) public List<MovementView> stockHistory(Long id){List<StockMovement> xs=id==null?stocks.findAllByOrderByOccurredAtDesc():stocks.findByProductIdOrderByOccurredAtDesc(id);return xs.stream().map(x->new MovementView(x.getId(),x.getProduct().getId(),x.getProduct().getName(),x.getType(),x.getReason(),x.getQuantity(),x.getBalanceAfter(),x.getReferenceId(),x.getNotes(),x.getOccurredAt())).toList();}
 @Transactional(readOnly=true) public List<MovementView> materialHistory(Long id){List<MaterialMovement> xs=id==null?materialMoves.findAllByOrderByOccurredAtDesc():materialMoves.findByMaterialIdOrderByOccurredAtDesc(id);return xs.stream().map(x->new MovementView(x.getId(),x.getMaterial().getId(),x.getMaterial().getName(),x.getType(),x.getReason(),x.getQuantity(),x.getBalanceAfter(),x.getReferenceId(),x.getNotes(),x.getOccurredAt())).toList();}
}
