package com.cestasdamel.erp.service;
import com.cestasdamel.erp.dto.Requests.*; import com.cestasdamel.erp.dto.Responses.*; import com.cestasdamel.erp.exception.*; import com.cestasdamel.erp.model.*; import com.cestasdamel.erp.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@Service @RequiredArgsConstructor
public class OperationsService {
 private final SaleRepository sales; private final PurchaseRepository purchases; private final ExpenseRepository expenses; private final BasketTemplateRepository baskets; private final InventoryService inventory; private final FinanceService finance;
 @Transactional public BasketView assemble(Long basketId,Assembly r){BasketTemplate b=baskets.findDetailed(basketId).orElseThrow(()->new NotFoundException("Cesta",basketId));int count=r.quantity();for(BasketProduct c:b.getProducts()){Product p=inventory.lockProduct(c.getProduct().getId());inventory.remove(p,c.getQuantity().multiply(BigDecimal.valueOf(count)),Enums.MovementReason.BASKET_PRODUCTION,basketId,r.notes(),Instant.now());}for(BasketMaterial c:b.getMaterials()){Material m=inventory.lockMaterial(c.getMaterial().getId());inventory.remove(m,c.getQuantity().multiply(BigDecimal.valueOf(count)),Enums.MovementReason.BASKET_PRODUCTION,basketId,r.notes(),Instant.now());}b.setAssembledQuantity(b.getAssembledQuantity()+count);return ViewMapper.basket(b);
 }
 @Transactional public SaleView sale(SaleInput r){Instant at=r.soldAt()==null?Instant.now():r.soldAt();Sale s=new Sale();s.setSoldAt(at);s.setPaymentMethod(r.paymentMethod());s.setObservations(r.observations());s.setTotal(BigDecimal.ZERO);sales.save(s);BigDecimal total=BigDecimal.ZERO;for(SaleLine line:r.items()){SaleItem item=new SaleItem();item.setSale(s);item.setItemType(line.type());item.setReferenceId(line.referenceId());item.setQuantity(line.quantity());BigDecimal price;if(line.type()==Enums.ItemType.PRODUCT){Product p=inventory.lockProduct(line.referenceId());if(!p.isActive())throw new BusinessException("Produto inativo: "+p.getName());inventory.remove(p,line.quantity(),Enums.MovementReason.SALE,s.getId(),"Venda",at);item.setItemName(p.getName());price=line.unitPrice()==null?p.getSalePrice():line.unitPrice();}else if(line.type()==Enums.ItemType.BASKET){if(line.quantity().stripTrailingZeros().scale()>0)throw new BusinessException("Quantidade de cestas deve ser inteira");BasketTemplate b=baskets.lockById(line.referenceId()).orElseThrow(()->new NotFoundException("Cesta",line.referenceId()));int q=line.quantity().intValueExact();if(b.getAssembledQuantity()<q)throw new BusinessException("Cestas montadas insuficientes de "+b.getName());b.setAssembledQuantity(b.getAssembledQuantity()-q);item.setItemName(b.getName());price=line.unitPrice()==null?b.getSalePrice():line.unitPrice();}else throw new BusinessException("Venda aceita apenas PRODUCT ou BASKET");item.setUnitPrice(price);item.setSubtotal(price.multiply(line.quantity()));s.getItems().add(item);total=total.add(item.getSubtotal());}s.setTotal(total);sales.save(s);finance.create(Enums.TransactionType.INCOME,Enums.TransactionSource.SALE,s.getId(),"Venda #"+s.getId(),total,at);return ViewMapper.sale(s);}
 @Transactional public PurchaseView purchase(PurchaseInput r){Instant at=r.purchasedAt()==null?Instant.now():r.purchasedAt();Purchase p=new Purchase();p.setEstablishment(r.establishment());p.setPurchasedAt(at);p.setObservations(r.observations());p.setTotal(BigDecimal.ZERO);purchases.save(p);BigDecimal total=BigDecimal.ZERO;for(PurchaseLine line:r.items()){PurchaseItem item=new PurchaseItem();item.setPurchase(p);item.setItemType(line.type());item.setReferenceId(line.referenceId());item.setQuantity(line.quantity());item.setUnitCost(line.unitCost());item.setSubtotal(line.unitCost().multiply(line.quantity()));if(line.type()==Enums.ItemType.PRODUCT){Product x=inventory.lockProduct(line.referenceId());inventory.add(x,line.quantity(),Enums.MovementReason.PURCHASE,p.getId(),"Compra em "+r.establishment(),at);x.setPurchasePrice(line.unitCost());item.setItemName(x.getName());}else if(line.type()==Enums.ItemType.MATERIAL){Material x=inventory.lockMaterial(line.referenceId());inventory.add(x,line.quantity(),Enums.MovementReason.PURCHASE,p.getId(),"Compra em "+r.establishment(),at);x.setUnitCost(line.unitCost());item.setItemName(x.getName());}else throw new BusinessException("Compra aceita apenas PRODUCT ou MATERIAL");p.getItems().add(item);total=total.add(item.getSubtotal());}p.setTotal(total);purchases.save(p);finance.create(Enums.TransactionType.EXPENSE,Enums.TransactionSource.PURCHASE,p.getId(),"Compra #"+p.getId()+" - "+p.getEstablishment(),total,at);return ViewMapper.purchase(p);}
 @Transactional public ExpenseView expense(ExpenseInput r){Expense e=new Expense();e.setDescription(r.description());e.setCategory(r.category());e.setOccurredAt(r.occurredAt()==null?Instant.now():r.occurredAt());e.setAmount(r.amount());e.setObservations(r.observations());expenses.save(e);finance.create(Enums.TransactionType.EXPENSE,Enums.TransactionSource.EXPENSE,e.getId(),e.getDescription(),e.getAmount(),e.getOccurredAt());return ViewMapper.expense(e);}
 @Transactional(readOnly=true) public List<SaleView> sales(){return sales.findAllByOrderBySoldAtDesc().stream().map(ViewMapper::sale).toList();}
 @Transactional(readOnly=true) public List<PurchaseView> purchases(){return purchases.findAllByOrderByPurchasedAtDesc().stream().map(ViewMapper::purchase).toList();}
 @Transactional(readOnly=true) public List<ExpenseView> expenses(){return expenses.findAllByOrderByOccurredAtDesc().stream().map(ViewMapper::expense).toList();}
}
