package com.cestasdamel.erp.service;
import com.cestasdamel.erp.dto.Responses.*; import com.cestasdamel.erp.model.Enums.StockStatus; import com.cestasdamel.erp.repository.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.*;
@Service
public class ReportingService {private final SaleRepository sales;private final PurchaseRepository purchases;private final ExpenseRepository expenses;private final ProductRepository products;private final MaterialRepository materials;private final BasketTemplateRepository baskets;private final FinancialTransactionRepository finance;private final ZoneId businessZone;
 public ReportingService(SaleRepository sales,PurchaseRepository purchases,ExpenseRepository expenses,ProductRepository products,MaterialRepository materials,BasketTemplateRepository baskets,FinancialTransactionRepository finance,@Value("${app.business-zone}") String businessZone){this.sales=sales;this.purchases=purchases;this.expenses=expenses;this.products=products;this.materials=materials;this.baskets=baskets;this.finance=finance;this.businessZone=ZoneId.of(businessZone);}
 private Instant start(LocalDate d){return d.atStartOfDay(businessZone).toInstant();}
 @Transactional(readOnly=true) public Dashboard dashboard(){LocalDate now=LocalDate.now(businessZone);Instant day=start(now),next=start(now.plusDays(1)),month=start(now.withDayOfMonth(1)),nextMonth=start(now.withDayOfMonth(1).plusMonths(1));var ps=products.findAll();var ms=materials.findAll();var recent=finance.findAllByOrderByOccurredAtDesc().stream().limit(10).map(ViewMapper::financial).toList();return new Dashboard(finance.balance(),sales.sumBetween(day,next),sales.sumBetween(month,nextMonth),expenses.sumBetween(day,next),expenses.sumBetween(month,nextMonth),purchases.sumBetween(month,nextMonth),sales.countBySoldAtGreaterThanEqualAndSoldAtLessThan(day,next),ps.stream().filter(p->ViewMapper.status(p.getQuantity(),p.getMinimumStock())==StockStatus.LOW).count(),ps.stream().filter(p->p.getQuantity().signum()<=0).count(),ms.stream().filter(m->ViewMapper.status(m.getQuantity(),m.getMinimumStock())==StockStatus.LOW).count(),ms.stream().filter(m->m.getQuantity().signum()<=0).count(),baskets.findAll().stream().mapToInt(x->x.getAssembledQuantity()).sum(),recent);}
 @Transactional(readOnly=true) public MonthlySummary monthly(int year,int month){YearMonth ym=YearMonth.of(year,month);Instant from=start(ym.atDay(1)),to=start(ym.plusMonths(1).atDay(1));BigDecimal s=sales.sumBetween(from,to),p=purchases.sumBetween(from,to),e=expenses.sumBetween(from,to);return new MonthlySummary(year,month,s,p,e,finance.balanceBetween(from,to));}
}
