package com.cestasdamel.erp.service;
import com.cestasdamel.erp.dto.Responses.*; import com.cestasdamel.erp.model.*; import static com.cestasdamel.erp.model.Enums.StockStatus.*; import java.math.BigDecimal;
public final class ViewMapper { private ViewMapper(){}
 public static Enums.StockStatus status(BigDecimal q,BigDecimal min){return q.signum()<=0?OUT_OF_STOCK:(q.compareTo(min)<=0?LOW:OK);}
 public static CategoryView category(ItemCategory c){return c==null?null:new CategoryView(c.getId(),c.getName(),c.getType());}
 public static ProductView product(Product p){return new ProductView(p.getId(),p.getName(),p.getDescription(),category(p.getCategory()),p.getUnit(),p.getQuantity(),p.getMinimumStock(),p.getPurchasePrice(),p.getSalePrice(),p.isActive(),status(p.getQuantity(),p.getMinimumStock()),p.getContentQuantity(),p.getContentUnit(),p.getImageData()!=null&&p.getImageData().length>0,p.getUpdatedAt()==null?null:p.getUpdatedAt().toEpochMilli());}
 public static MaterialView material(Material m){return new MaterialView(m.getId(),m.getName(),m.getDescription(),category(m.getCategory()),m.getUnit(),m.getQuantity(),m.getMinimumStock(),m.getUnitCost(),m.isActive(),status(m.getQuantity(),m.getMinimumStock()),m.getContentQuantity(),m.getContentUnit());}
 public static BasketView basket(BasketTemplate b){return basket(b,BigDecimal.ZERO);}
 public static BasketView basket(BasketTemplate b,BigDecimal maximum){return new BasketView(b.getId(),b.getName(),b.getDescription(),b.getSalePrice(),b.getStockQuantity(),b.getMinimumStock(),b.isActive(),status(b.getStockQuantity(),b.getMinimumStock()),maximum,b.getProducts().stream().map(x->new ComponentView(x.getProduct().getId(),x.getProduct().getName(),x.getQuantity(),x.getProduct().getUnit())).toList(),b.getMaterials().stream().map(x->new ComponentView(x.getMaterial().getId(),x.getMaterial().getName(),x.getQuantity(),x.getMaterial().getUnit())).toList());}
 public static SaleView sale(Sale s){return new SaleView(s.getId(),s.getSoldAt(),s.getPaymentMethod(),s.getTotal(),s.getStatus(),s.getObservations(),s.getCancelledAt(),s.getCancellationReason(),s.getItems().stream().map(x->new ItemView(x.getId(),x.getItemType(),x.getReferenceId(),x.getItemName(),x.getQuantity(),x.getUnitPrice(),x.getSubtotal())).toList());}
 public static ProductionView production(ProductionOrder p){return new ProductionView(p.getId(),p.getBasket().getId(),p.getBasket().getName(),p.getQuantity(),p.getUnitCost(),p.getUnitCost().multiply(p.getQuantity()),p.getProducedAt(),p.getResponsible(),p.getNotes(),p.getStatus());}
 public static PurchaseView purchase(Purchase p){return new PurchaseView(p.getId(),p.getEstablishment(),p.getPurchasedAt(),p.getTotal(),p.getObservations(),p.getItems().stream().map(x->new ItemView(x.getId(),x.getItemType(),x.getReferenceId(),x.getItemName(),x.getQuantity(),x.getUnitCost(),x.getSubtotal())).toList(),p.getReceiptAccessKey());}
 public static ExpenseView expense(Expense e){return new ExpenseView(e.getId(),e.getDescription(),e.getCategory(),e.getOccurredAt(),e.getAmount(),e.getObservations());}
 public static FinancialView financial(FinancialTransaction f){return new FinancialView(f.getId(),f.getType(),f.getSource(),f.getReferenceId(),f.getDescription(),f.getAmount(),f.getOccurredAt());}
}
