package com.cestasdamel.erp.controller;
import com.cestasdamel.erp.dto.Requests.*; import com.cestasdamel.erp.dto.Responses.*; import com.cestasdamel.erp.service.CatalogService; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.util.*;
@RestController @RequiredArgsConstructor public class CatalogController {private final CatalogService service;
 @GetMapping("/products") List<ProductView> products(){return service.products();}@PostMapping("/products") ResponseEntity<ProductView> product(@Valid @RequestBody ProductInput r){return ResponseEntity.status(201).body(service.saveProduct(null,r));}@PutMapping("/products/{id}") ProductView product(@PathVariable Long id,@Valid @RequestBody ProductInput r){return service.saveProduct(id,r);}
 @PutMapping(value="/products/{id}/image",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ProductView image(@PathVariable Long id,@RequestPart("file") MultipartFile file){return service.saveProductImage(id,file);}
 @GetMapping("/products/{id}/image") ResponseEntity<byte[]> image(@PathVariable Long id){var image=service.productImage(id);return ResponseEntity.ok().contentType(MediaType.parseMediaType(image.contentType())).cacheControl(CacheControl.noStore()).body(image.data());}
 @DeleteMapping("/products/{id}/image") ResponseEntity<Void> deleteImage(@PathVariable Long id){service.deleteProductImage(id);return ResponseEntity.noContent().build();}
 @DeleteMapping("/products/{id}") ResponseEntity<Void> deleteProduct(@PathVariable Long id){service.deleteProduct(id);return ResponseEntity.noContent().build();}
 @GetMapping("/materials") List<MaterialView> materials(){return service.materials();}@PostMapping("/materials") ResponseEntity<MaterialView> material(@Valid @RequestBody MaterialInput r){return ResponseEntity.status(201).body(service.saveMaterial(null,r));}@PutMapping("/materials/{id}") MaterialView material(@PathVariable Long id,@Valid @RequestBody MaterialInput r){return service.saveMaterial(id,r);}
 @DeleteMapping("/materials/{id}") ResponseEntity<Void> deleteMaterial(@PathVariable Long id){service.deleteMaterial(id);return ResponseEntity.noContent().build();}
 @GetMapping("/baskets") List<BasketView> baskets(){return service.baskets();}@GetMapping("/baskets/{id}") BasketView basket(@PathVariable Long id){return service.basket(id);}@PostMapping("/baskets") ResponseEntity<BasketView> basket(@Valid @RequestBody BasketInput r){return ResponseEntity.status(201).body(service.saveBasket(null,r));}@PutMapping("/baskets/{id}") BasketView basket(@PathVariable Long id,@Valid @RequestBody BasketInput r){return service.saveBasket(id,r);}
 @DeleteMapping("/baskets/{id}") ResponseEntity<Void> deleteBasket(@PathVariable Long id){service.deleteBasket(id);return ResponseEntity.noContent().build();}
}
